# Site settings
title: Maggie's Profile
email: minyisme@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bio
baseurl: "/patchwork-gh-pages-24"
url: "http://minyisme.github.io"
twitter_username: maggieminyang
github_username:  minyisme
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
